<?php
require('fpdf/fpdf.php');
include "connection.php";

if (!isset($_GET['ids'])) {
    die("No entries selected.");
}

$ids = explode(",", $_GET['ids']);
$ids = array_map('intval', $ids);
$idList = implode(",", $ids);

$result = $conn->query("SELECT * FROM entries WHERE id IN ($idList)");

class PDF_Clearance extends FPDF {
    function Header() {
        // Left logo
        $this->Image('asset/img/deped_logo.png', 30, 14, 25);
        // Right logo
        $this->Image('asset/img/cam-norte.png', 155, 14, 25);

        // Header Text
        $this->SetTextColor(5, 5, 5);
        $this->SetFont('Times', 'B', 12);
        $this->Ln(5);
        $this->Cell(0, 5, 'Republic of the Philippines', 0, 1, 'C');
        $this->Cell(0, 5, 'Department of Education', 0, 1, 'C');
        $this->Cell(0, 5, 'Region V - Bicol', 0, 1, 'C');
        $this->Cell(0, 5, 'Schools Division Office', 0, 1, 'C');
        $this->Cell(0, 5, 'Camarines Norte', 0, 1, 'C');
        $this->Ln(5);
    }

    // Table Row for data
    function RowData($label, $value) {
        $this->SetFont('Arial', 'B', 11);
        $this->Cell(50, 8, $label . ":", 0, 0, 'L');
        $this->SetFont('Arial', '', 11);
        $this->MultiCell(0, 8, $value, 0, 'L');
        $this->Ln(1);
    }
}

$pdf = new PDF_Clearance();
$pdf->SetTitle("DepEd Clearance");

while ($row = $result->fetch_assoc()) {
$pdf->AddPage();
$purpose = $row['purposeOfClearance'];

// === COLORS ===
$labelColor = [100, 100, 100]; // gray for labels
$titleColor = [33, 37, 41];    // dark gray for titles
$lineColor = [200, 200, 200];  // light gray divider
$pdf->SetTextColor(5, 5, 5);
// === TITLE ===
$pdf->SetFont('Arial', 'B', 20);
$pdf->SetTextColor($titleColor[0], $titleColor[1], $titleColor[2]);
$pdf->Cell(0, 12, 'Clearance Information', 0, 1, 'C');
$pdf->Ln(4);

// Divider line
$pdf->SetDrawColor($lineColor[0], $lineColor[1], $lineColor[2]);
$pdf->SetLineWidth(0.3);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(5);

// === SECTION: Personal Information ===
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetTextColor($titleColor[0], $titleColor[1], $titleColor[2]);
$pdf->Cell(0, 8, "Personal Information", 0, 1, 'L');
$pdf->Ln(1);

$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor($labelColor[0], $labelColor[1], $labelColor[2]);
$pdf->RowData("Full Name", ucwords(strtolower($row['fullName'])));
$pdf->RowData("Position", ucfirst($row['position']));
$pdf->RowData("District", ucwords(strtolower($row['district'])));
$pdf->RowData("School", $row['school']);

$pdf->Ln(4);

// Divider line
$pdf->SetDrawColor($lineColor[0], $lineColor[1], $lineColor[2]);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(4);

// === SECTION: Clearance Details ===
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetTextColor($titleColor[0], $titleColor[1], $titleColor[2]);
$pdf->Cell(0, 8, "Clearance Details", 0, 1, 'L');
$pdf->Ln(1);

$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor($labelColor[0], $labelColor[1], $labelColor[2]);
$pdf->RowData("Purpose", ucwords(strtolower($purpose)));
$pdf->RowData("Date of Action", (!empty($row['dateOfAction']) && $row['dateOfAction'] !== '0000-00-00' ? date("M d, Y", strtotime($row['dateOfAction'])) : 'N/A'));
$pdf->RowData("Start Date", (!empty($row['startDate']) && $row['startDate'] !== '0000-00-00' ? date("M d, Y", strtotime($row['startDate'])) : 'N/A'));
$pdf->RowData("End Date", (!empty($row['endDate']) && $row['endDate'] !== '0000-00-00' ? date("M d, Y", strtotime($row['endDate'])) : 'N/A'));
$pdf->RowData("Remarks", ucfirst($row['additionalNote']));
$pdf->RowData("Date Signed by District", date("F d, Y", strtotime($row['schoolDistrictSigned'])));
$pdf->RowData("Date Signed by Division", date("F d, Y", strtotime($row['divisionSigned'])));

$pdf->Ln(8);

// Bottom Divider
$pdf->SetDrawColor($lineColor[0], $lineColor[1], $lineColor[2]);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(5);

// === FOOTER ===
$pdf->SetFont('Arial', 'I', 10);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 8, '*Generated by DepEd Division Clearance System', 0, 1, 'C');

}

$pdf->Output();
?>
